name: Commit Sign-off Check
on:
  workflow_dispatch:

jobs:
  # Checks that all commits contain sign-offs
  # Will add/remove comments as necessary based on the current status of the pull request.
  check-signed-commits:
    name: Check signed commits
    runs-on: ubuntu-latest
    steps:
      - uses: debezium/dbz/.github/actions/check-dco@main
        with:
          add-comments: "true"
