name: Build Connector Db2

on:
  push:
    paths:
      - 'debezium-core/**'
      - 'debezium-api/**'
  pull_request:
    paths:
      - 'debezium-core/**'
      - 'debezium-api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Core
        uses: actions/checkout@v2
        with:
          path: core
      - name: Checkout Db2
        uses: actions/checkout@v2
        with:
          repository: debezium/debezium-connector-db2
          path: db2
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Debezium Core
        run: mvn clean install -f core/pom.xml -DskipTests -DskipITs -Dformat.formatter.goal=validate -Dformat.imports.goal=check
      - name: Build Debezium Connector Db2
        run: mvn clean install -f db2/pom.xml -Passembly -Dformat.formatter.goal=validate -Dformat.imports.goal=check
