name: Build Connector Db2

on:
  push:
    branches:
      - master
      - 1.*
    paths:
      - 'debezium-core/**'
      - 'debezium-api/**'
      - 'debezium-parent/pom.xml'
      - 'debezium-bom/pom.xml'
      - 'pom.xml'
      - '.github/workflows/db2-workflow.yml'
  pull_request:
    branches:
      - master
      - 1.*
    paths:
      - 'debezium-core/**'
      - 'debezium-api/**'
      - 'debezium-parent/pom.xml'
      - 'debezium-bom/pom.xml'
      - 'pom.xml'
      - '.github/workflows/db2-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Core
        uses: actions/checkout@v2
        with:
          path: core
      - name: Checkout Db2
        uses: actions/checkout@v2
        with:
          repository: debezium/debezium-connector-db2
          path: db2
      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build Debezium Core
        run: mvn clean install -f core/pom.xml -DskipTests -DskipITs -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
      - name: Build Debezium Connector Db2
        run: mvn clean install -f db2/pom.xml -Passembly -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
