name: Build MongoDB Connector

on:
  push:
    branches:
      - main
      - 1.*
    paths:
      - 'support/checkstyle/**'
      - 'debezium-api/**'
      - 'debezium-assembly-descriptors/**'
      - 'debezium-core/**'
      - 'debezium-embedded/**'
      - 'debezium-connector-mongodb/**'
      - 'debezium-parent/pom.xml'
      - 'debezium-bom/pom.xml'
      - 'pom.xml'
      - '.github/workflows/mongodb-workflow.yml'
  pull_request:
    branches:
      - main
      - 1.*
    paths:
      - 'support/checkstyle/**'
      - 'debezium-api/**'
      - 'debezium-assembly-descriptors/**'
      - 'debezium-core/**'
      - 'debezium-embedded/**'
      - 'debezium-connector-mongodb/**'
      - 'debezium-parent/pom.xml'
      - 'debezium-bom/pom.xml'
      - 'pom.xml'
      - '.github/workflows/mongodb-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version-mongo-server: ["4.0", "4.2", "5.0"]
    steps:
      - uses: actions/checkout@v2
      - name: Setup java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Check changes in Debezium Connector MongoDB
        run: mvn clean install -B -pl debezium-connector-mongodb -am -Passembly -Dcheckstyle.skip=true -Dformat.skip=true -Drevapi.skip -Dversion.mongo.server=${{ matrix.version-mongo-server }} -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
