name: Build Server Workflow

on:
  push:
    branches:
      - main
      - 1.*
    paths:
      - 'support/checkstyle/**'
      - 'debezium-api/**'
      - 'debezium-assembly-descriptors/**'
      - 'debezium-core/**'
      - 'debezium-embedded/**'
      - 'debezium-server/**'
      - 'debezium-parent/pom.xml'
      - 'debezium-bom/pom.xml'
      - 'pom.xml'
      - '.github/workflows/server-workflow.yml'
  pull_request:
    branches:
      - main
      - 1.*
    paths:
      - 'support/checkstyle/**'
      - 'debezium-api/**'
      - 'debezium-assembly-descriptors/**'
      - 'debezium-core/**'
      - 'debezium-embedded/**'
      - 'debezium-server/**'
      - 'debezium-parent/pom.xml'
      - 'debezium-bom/pom.xml'
      - 'pom.xml'
      - '.github/workflows/server-workflow.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v2
      - name: Get Date
        id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y-%m")"
        shell: bash
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Cache Maven Repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: maven-server-${{ steps.get-date.outputs.date }}
          restore-keys: |
            maven-server-${{ steps.get-date.outputs.date }}
      - name: Run Formatting and Import Order Checks
        run: mvn process-resources -DskipTests=true -DskipITs=true -Dformat.formatter.goal=validate -Dformat.imports.goal=check -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
      - name: Build Debezium Server
        run: mvn clean install -B -pl debezium-testing/debezium-testing-testcontainers,debezium-server -Pserver-ci -am -amd -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
